#!/bin/bash
#mvn archetype:generate -DarchetypeArtifactId=clojure-maven-archetype \
#                       -DarchetypeGroupId=tk.skuro \
#                       -DarchetypeVersion=1.3
lein new app project
cd project
echo "To create standalone jar, `lein uberjar`" >> README.md
